### ISSUE TITLE
Broken links & Addition links in Documentation : README.md

### ISSUE THREAD

**Issue by reticent-roklimber** [COS-IT-FLOWS/Gather#14]
### Broken links in README.md
+ Certain links seem to be broken, especially ones in the Open Source section. Check and ensure that links point to correct addresses.
+ In License section, add link to Gather-documentation repository where the Creative Commons license has been mentioned.

**Comment by devikasiv** [comment]
Broken links have now been fixed and README has been updated to include link to documentation site -- in the `documentation` branch.
