### ISSUE TITLE
Update README.md to include required details

### ISSUE THREAD

**Issue by reticent-roklimber** [COS-IT-FLOWS/Gather#7]
Update README to include details for the project:
+ Features
+ Technology Stack
+ Link to Code of Conduct, Contribute & Documentation website
+ Testing methodology and framework
+ Code Test Coverage

**Comment by devikasiv** [comment]
Updated README.md to include all mentioned files except Testing Methodology and Framework, Code Test Coverage

**Comment by devikasiv** [comment]
Add Testing Methodology and Framework to README.md
